//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетСИЗ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class БелкаФаворитСпичечнаяФабрикаБазаДанныхEntities : DbContext
    {
        public БелкаФаворитСпичечнаяФабрикаБазаДанныхEntities()
            : base("name=БелкаФаворитСпичечнаяФабрикаБазаДанныхEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Выдача> Выдача { get; set; }
        public virtual DbSet<ДерматологическоеСредство> ДерматологическоеСредство { get; set; }
        public virtual DbSet<Инфраструктура> Инфраструктура { get; set; }
        public virtual DbSet<НормаВыдачи> НормаВыдачи { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Профессия> Профессия { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Сезон> Сезон { get; set; }
        public virtual DbSet<СИЗ> СИЗ { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<ТипСИЗ> ТипСИЗ { get; set; }
    }
}
