//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетСИЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выдача
    {
        public int id_Выдачи { get; set; }
        public int id_сотрудника { get; set; }
        public int id_сиз { get; set; }
        public System.DateTime Дата_выдачи { get; set; }
        public int количество { get; set; }
        public Nullable<System.DateTime> Срок_износа { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public System.DateTime Дата_изменения { get; set; }
        public Nullable<int> Кем_создана { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual СИЗ СИЗ { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
