//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетСИЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияВхода
    {
        public int id_Записи { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public System.DateTime Время_входа_в_систему { get; set; }
        public string Система { get; set; }
        public string IP_adress { get; set; }
        public bool Успех { get; set; }
        public string Причина_отказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
