//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетСИЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class НормаВыдачи
    {
        public int id_Нормы { get; set; }
        public int id_профессии { get; set; }
        public int id_сиз { get; set; }
        public string Норма_в_единицах_измерения { get; set; }
        public string Период { get; set; }
        public int Сезон { get; set; }
        public string Основание_назначения { get; set; }
    
        public virtual Профессия Профессия { get; set; }
        public virtual Сезон Сезон1 { get; set; }
        public virtual СИЗ СИЗ { get; set; }
    }
}
