//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетСИЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Профессия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Профессия()
        {
            this.ДерматологическоеСредство = new HashSet<ДерматологическоеСредство>();
            this.НормаВыдачи = new HashSet<НормаВыдачи>();
            this.Сотрудник = new HashSet<Сотрудник>();
        }
    
        public int id_Профессии_или_должности { get; set; }
        public string Наименование { get; set; }
        public string Код_по_нормативу { get; set; }
        public int id_инфраструктуры_или_отдела { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДерматологическоеСредство> ДерматологическоеСредство { get; set; }
        public virtual Инфраструктура Инфраструктура { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<НормаВыдачи> НормаВыдачи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }
    }
}
