//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетСИЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class СИЗ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СИЗ()
        {
            this.Выдача = new HashSet<Выдача>();
            this.НормаВыдачи = new HashSet<НормаВыдачи>();
        }
    
        public int id_СИЗ { get; set; }
        public string Наименование { get; set; }
        public int id_типаСИЗ { get; set; }
        public string Единица_измерения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдача> Выдача { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<НормаВыдачи> НормаВыдачи { get; set; }
        public virtual ТипСИЗ ТипСИЗ { get; set; }
    }
}
